### ISSUE TITLE
Service Bus Webjob MessageHandlerOptions for ExceptionReceivedHandler ignored by Service Bus Listener

### ISSUE THREAD

**Issue by GMacAussie** [Azure/azure-functions-servicebus-extension#166]
It appears that the Service Bus Listener is not being passed the `ExceptionReceivedHandler ` that is configured for Service Bus webjobs. The `ServiceBusTriggerAttributeBindingProvider.GetServiceBusOptions()` method calls the `DeepClone()` method in `ServiceBusOptions` which does not copy the handler, and thus the `ServiceBusListener` will have the default handler.

Note that we are trying to manage transient the exceptions for `ServiceBusException`, but we have not got that far yet because of this issue.

Our webjobs configuration for Service Bus:

```
Service Bus webjob configuration
   builder.AddServiceBus(options => {
       options.PrefetchCount = 64;
       options.ConnectionString = ConfigurationManager.ConnectionStrings["ServiceBusConnection"].ConnectionString;
       options.BatchOptions.AutoComplete = false;
       options.BatchOptions.MaxMessageCount = 64;
       options.MessageHandlerOptions = new MessageHandlerOptions(ServiceBusExceptionReceived) {
           AutoComplete = false,
           MaxConcurrentCalls = 16
       };
```
Our `ExceptionReceivedHandler Func<>` handler:

```
protected static Task ServiceBusExceptionReceived(ExceptionReceivedEventArgs exceptionReceivedEventArgs) {
    // TODO: Remove!
    logger.Info(exceptionReceivedEventArgs.Exception, "ServiceBusExceptionReceived execption received");

    // check if this is a service bus exception or it is not a transient
    if ((exceptionReceivedEventArgs.Exception as ServiceBusException)?.IsTransient ?? false) {
        // use the backoff logger to only log 5 or more of these in a short period
        QueueLogger.Warn(exceptionReceivedEventArgs.Exception);
    } else {
        // throw as regular exception
        throw exceptionReceivedEventArgs.Exception;
    }

    return Task.CompletedTask;
}
```

Actual behaviour:
The default exception handler called by Service Bus Listener is used.

```
2021-07-14T12:17:02.6335713Z ERROR Microsoft.Azure.WebJobs.ServiceBus.Listeners.ServiceBusListener: An unhandled exception occurred in the message batch receive loop Microsoft.Azure.ServiceBus.ServiceBusCommunicationException: The connection was inactive for more than the allowed 60000 milliseconds and is closed by container '8848012a-a14a-491a-8174-c5fffd5e41a6'. ---> Microsoft.Azure.ServiceBus.ServiceBusException: The connection was inactive for more than the allowed 60000 milliseconds and is closed by container '8848012a-a14a-491a-8174-c5fffd5e41a6'.
   at Microsoft.Azure.ServiceBus.Core.MessageReceiver.d__88.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.Azure.ServiceBus.Core.MessageReceiver.d__88.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.ServiceBus.Core.MessageReceiver.<>c__DisplayClass65_0.<b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.ServiceBus.RetryPolicy.d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Azure.ServiceBus.RetryPolicy.d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.ServiceBus.Core.MessageReceiver.d__65.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Azure.WebJobs.ServiceBus.Listeners.ServiceBusListener.<>c__DisplayClass35_0.<b__0>d.MoveNext()
Microsoft.Azure.ServiceBus.ServiceBusException: The connection was inactive for more than the allowed 60000 milliseconds and is closed by container '8848012a-a14a-491a-8174-c5fffd5e41a6'.
   at Microsoft.Azure.ServiceBus.Core.MessageReceiver.d__88.MoveNext()
```
   
Expected behaviour:
The provided exception handler configured for Service Bus webjobs is used.

Packages
Microsoft.Azure.WebJobs.Extensions.ServiceBus 4.3.0

**Comment by alrod** [comment]
validate if it works in track2, close if it works in v2

**Comment by lilyjma** [comment]
@GMacAussie - Are you still experiencing the problem in the issue? If using the latest version of the extension doesn't solve the problem, please let us know. The new version is:  https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.ServiceBus

**Comment by GMacAussie** [comment]
@lilyjma - I am not quite sure what you mean. We are now running 5.8.1 but use a logging filter to work around the above problem. We left the original hook in place but have not seen anything (it would suppress reports on transient errors), so that doesn't say much.

We did not review this issue since this ticket is still open. Is that not the case and that this issue has been addressed (and which version if so)?

**Comment by lilyjma** [comment]
@GMacAussie - Thanks for the reply. Originally you mentioned using Microsoft.Azure.WebJobs.Extensions.ServiceBus 4.3.0 in the issue, so we wanted to make sure if this is still a problem with the newer version of the extension. Looks like you're now using the newer version but are using a logging filter so it's difficult to know. We haven't gotten a chance to investigate this further, so I can't answer your question. I'll leave this issue open for when we can get to this.
