### ISSUE TITLE
ServiceBusTrigger continously logs warnings about "The operation did not complete within the allocated time 00:01:00 for object receiverNNN"

### ISSUE THREAD

**Issue by marnilss** [Azure/azure-functions-servicebus-extension#181]
We have a Function App running in Azure, with a ServiceBusTrigger configured.
And while it is running, twice every minute, it will log a warning for:
```
RunOperation encountered an exception and will retry. Exception: Azure.Messaging.ServiceBus.ServiceBusException: The operation did not complete within the allocated time 00:01:00 for object receiver596. (ServiceTimeout)
 ---> System.TimeoutException: The operation did not complete within the allocated time 00:01:00 for object receiver596.
   at Microsoft.Azure.Amqp.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.Azure.Amqp.AmqpObject.OpenAsyncResult.End(IAsyncResult result)
   at Microsoft.Azure.Amqp.AmqpObject.EndOpen(IAsyncResult result)
   at Microsoft.Azure.Amqp.AmqpObject.<>c.<OpenAsync>b__51_1(IAsyncResult r)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location ---
   at Azure.Messaging.ServiceBus.Amqp.AmqpConnectionScope.OpenAmqpObjectAsync(AmqpObject target, TimeSpan timeout, CancellationToken cancellationToken, String entityPath)
   at Azure.Messaging.ServiceBus.Amqp.AmqpConnectionScope.OpenReceiverLinkAsync(String identifier, String entityPath, TimeSpan timeout, UInt32 prefetchCount, ServiceBusReceiveMode receiveMode, String sessionId, Boolean isSessionReceiver, CancellationToken cancellationToken)
   at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver.OpenReceiverLinkAsync(TimeSpan timeout, UInt32 prefetchCount, ServiceBusReceiveMode receiveMode, String identifier, CancellationToken cancellationToken)
   at Microsoft.Azure.Amqp.FaultTolerantAmqpObject`1.OnCreateAsync(TimeSpan timeout)
   at Microsoft.Azure.Amqp.Singleton`1.GetOrCreateAsync(TimeSpan timeout)
   at Microsoft.Azure.Amqp.Singleton`1.GetOrCreateAsync(TimeSpan timeout)
   at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver.<>c.<<OpenLinkAsync>b__72_0>d.MoveNext()
--- End of stack trace from previous location ---
   at Azure.Messaging.ServiceBus.ServiceBusRetryPolicy.RunOperation[T1,TResult](Func`4 operation, T1 t1, TransportConnectionScope scope, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
```
Category: Azure.Messaging.ServiceBus
LogLevel: Warning
EventName: RunOperationExceptionEncountered

I spent about 1 working-day troubleshooting this, until I realized it is actually fully functional, and I guess the behavior is part of the intented implementation. BUT logging this with loglevel warning should not be done then.

Nuget packages:
Microsoft.Azure.WebJobs.Extensions.ServiceBus, 5.2.0
Microsoft.NET.Sdk.Functions, 4.0.1

**Comment by mathiasbl** [comment]
Also noticed this yesterday and today. Same version.

**Comment by slanto** [comment]
I am developing an azure function running in-process based on .net6. Function is triggered by a service bus. 

I can confirm that I am struggling with the same problem described by @marnilss.  

After running the function locally as well as in the Azure directly, it is logging the following warnings: 

```
RunOperation encountered an exception and will retry. Exception: Azure.Messaging.ServiceBus.ServiceBusException: The operation did not complete within the allocated time 00:01:00 for object receiver16. (ServiceTimeout)
 ---> System.TimeoutException: The operation did not complete within the allocated time 00:01:00 for object receiver16.
   at Microsoft.Azure.Amqp.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.Azure.Amqp.AmqpObject.OpenAsyncResult.End(IAsyncResult result)
   at Microsoft.Azure.Amqp.AmqpObject.EndOpen(IAsyncResult result)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location ---
   at Azure.Messaging.ServiceBus.Amqp.AmqpConnectionScope.OpenAmqpObjectAsync(AmqpObject target, TimeSpan timeout, CancellationToken cancellationToken, String entityPath)
   at Azure.Messaging.ServiceBus.Amqp.AmqpConnectionScope.OpenReceiverLinkAsync(String identifier, String entityPath, TimeSpan timeout, UInt32 prefetchCount, ServiceBusReceiveMode receiveMode, String sessionId, Boolean isSessionReceiver, CancellationToken cancellationToken)
   at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver.OpenReceiverLinkAsync(TimeSpan timeout, UInt32 prefetchCount, ServiceBusReceiveMode receiveMode, String identifier, CancellationToken cancellationToken)
   at Microsoft.Azure.Amqp.FaultTolerantAmqpObject`1.OnCreateAsync(TimeSpan timeout, CancellationToken cancellationToken)
   at Microsoft.Azure.Amqp.Singleton`1.GetOrCreateAsync(TimeSpan timeout, CancellationToken cancellationToken)
   at Microsoft.Azure.Amqp.Singleton`1.GetOrCreateAsync(TimeSpan timeout, CancellationToken cancellationToken)
   at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver.<>c.<<OpenLinkAsync>b__72_0>d.MoveNext()
--- End of stack trace from previous location ---
   at Azure.Messaging.ServiceBus.ServiceBusRetryPolicy.RunOperation[T1,TResult](Func`4 operation, T1 t1, TransportConnectionScope scope, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
```

Context

Function configuration:
```
<TargetFramework>net6.0</TargetFramework>
<AzureFunctionsVersion>v4</AzureFunctionsVersion>
```
Nuget packages:

```
<PackageReference Include="Microsoft.Azure.WebJobs.Extensions.ServiceBus" Version="5.3.0" />
<PackageReference Include="Microsoft.Azure.WebJobs.Host.Storage" Version="4.0.4" />
<PackageReference Include="Microsoft.NET.Sdk.Functions" Version="4.1.0" />
```

**Comment by bpellens** [comment]
Hello,

In our Azure Functions, we have encountered the same behavior. However, while further investigating, we noticed that it also occurs while service bus processor from a console application. The root cause seems to be in the Azure.Messaging.ServiceBus library.

`var processor = _serviceBusClient.CreateSessionProcessor(queueName, new ServiceBusSessionProcessorOptions() { AutoCompleteMessages = false });
processor.ProcessMessageAsync += (args) => ProcessMessagesAsync(args, handler);
processor.ProcessErrorAsync += ProcessErrorAsync;
await processor.StartProcessingAsync(stoppingToken);`

We used version 7.7.0 of the Azure.Messaging.ServiceBus library in a .NET 6 console application. We also notice that it is only occurring, or occurring more, while using session based queues. I don't know if this is case in the reportings above by @marnilss and @slanto

**Comment by danielabbatt** [comment]
I'm getting the same using an isolated worker on Azure functions v5 and .NET 6.

**Comment by danielabbatt** [comment]
Seems related: https://github.com/Azure/azure-webjobs-sdk/issues/2784

**Comment by slanto** [comment]
> Hello,
> 
> In our Azure Functions, we have encountered the same behavior. However, while further investigating, we noticed that it also occurs while service bus processor from a console application. The root cause seems to be in the Azure.Messaging.ServiceBus library.
> 
> `var processor = _serviceBusClient.CreateSessionProcessor(queueName, new ServiceBusSessionProcessorOptions() { AutoCompleteMessages = false }); processor.ProcessMessageAsync += (args) => ProcessMessagesAsync(args, handler); processor.ProcessErrorAsync += ProcessErrorAsync; await processor.StartProcessingAsync(stoppingToken);`
> 
> We used version 7.7.0 of the Azure.Messaging.ServiceBus library in a .NET 6 console application. We also notice that it is only occurring, or occurring more, while using session based queues. I don't know if this is case in the reportings above by @marnilss and @slanto ?

In my case it is `Azure.Messaging.ServiceBus` in 7.6.0 version. I am also using `IsSessionsEnabled = true` on the ServiceBusTrigger

**Comment by fandrusi** [comment]
Struggling with the same thing here. I really hate this messaging.. especially since it's followed up with an Exception Call Stack.  Very misleading. I did find another github entry where this was originally categorized as an Error in the log which was downgraded to a Warning...   

https://github.com/Azure/Azure-Functions/issues/993

Seeing the exception details really makes it look like something bad happened.

**Comment by marnilss** [comment]
> > Hello,
> > In our Azure Functions, we have encountered the same behavior. However, while further investigating, we noticed that it also occurs while service bus processor from a console application. The root cause seems to be in the Azure.Messaging.ServiceBus library.
> > `var processor = _serviceBusClient.CreateSessionProcessor(queueName, new ServiceBusSessionProcessorOptions() { AutoCompleteMessages = false }); processor.ProcessMessageAsync += (args) => ProcessMessagesAsync(args, handler); processor.ProcessErrorAsync += ProcessErrorAsync; await processor.StartProcessingAsync(stoppingToken);`
> > We used version 7.7.0 of the Azure.Messaging.ServiceBus library in a .NET 6 console application. We also notice that it is only occurring, or occurring more, while using session based queues. I don't know if this is case in the reportings above by @marnilss and @slanto ?
> 
> In my case it is `Azure.Messaging.ServiceBus` in 7.6.0 version. I am also using `IsSessionsEnabled = true` on the ServiceBusTrigger



> Hello,
> 
> In our Azure Functions, we have encountered the same behavior. However, while further investigating, we noticed that it also occurs while service bus processor from a console application. The root cause seems to be in the Azure.Messaging.ServiceBus library.
> 
> `var processor = _serviceBusClient.CreateSessionProcessor(queueName, new ServiceBusSessionProcessorOptions() { AutoCompleteMessages = false }); processor.ProcessMessageAsync += (args) => ProcessMessagesAsync(args, handler); processor.ProcessErrorAsync += ProcessErrorAsync; await processor.StartProcessingAsync(stoppingToken);`
> 
> We used version 7.7.0 of the Azure.Messaging.ServiceBus library in a .NET 6 console application. We also notice that it is only occurring, or occurring more, while using session based queues. I don't know if this is case in the reportings above by @marnilss and @slanto ?

We are using session based queues, when seeing these warnings.
