### ISSUE TITLE
SessionLockLost exception occurs when queue has messages from two or more different sessions

### ISSUE THREAD

**Issue by alex-zyl** [Azure/azure-functions-servicebus-extension#23]
Prerequisites:
1. Webjob with Microsoft.Azure.WebJobs.Extensions.ServiceBus 3.1.0-beta4
2. An existing SB sessioned queue with messages with different session ids
3. Webjob function accepting raw Message and ISessionProvider
3. Session handler configuration
```
AutoComplete = false,
MaxConcurrentSessions = 30,
MaxAutoRenewDuration = TimeSpan.FromMinutes(30)
```

Upon running webjob instance message processing fails for one of the first received messages when completing\abandoning a message

```
[19:12:24 INF] Executing 'MessageProcessorWebJob.ProcessMessageAsync' (Reason='New ServiceBus message detected on 'live-messages'.', Id=036c3ec2-f4e1-4a97-9a62-2a4d4527eefe)
[19:12:24 INF] Executing 'MessageProcessorWebJob.ProcessMessageAsync' (Reason='New ServiceBus message detected on 'live-messages'.', Id=f8ec0157-c479-4338-aea6-dc0072a53912)
[19:12:24 INF] Trigger Details: MessageId: 8b4e98d43e13457ea48dc12685a476e8, DeliveryCount: 1, EnqueuedTime: 04-09-19 16:10:49, LockedUntil: 31-12-99 23:59:59, SessionId: 2019_0703_LS007
[19:12:24 INF] Trigger Details: MessageId: 85e317a4ae41467d9c79fc58d9657286, DeliveryCount: 1, EnqueuedTime: 04-09-19 16:10:46, LockedUntil: 31-12-99 23:59:59, SessionId: 2019_0466_LS009
[19:12:24 WRN] Processing message 85e317a4ae41467d9c79fc58d9657286 for session 2019_0466_LS009.
[19:12:24 WRN] Processing message 8b4e98d43e13457ea48dc12685a476e8 for session 2019_0703_LS007. 
[19:12:29 WRN] Finished processing message 85e317a4ae41467d9c79fc58d9657286 for session 2019_0466_LS009
[19:12:29 WRN] The exception was thrown on message handling. Message handling will be retried.
Microsoft.Azure.ServiceBus.SessionLockLostException: The session lock has expired on the MessageSession. Accept a new MessageSession.
   at Microsoft.Azure.ServiceBus.Core.MessageReceiver.DisposeMessagesAsync(IEnumerable`1 lockTokens, Outcome outcome)
   at Microsoft.Azure.ServiceBus.RetryPolicy.RunOperation(Func`1 operation, TimeSpan operationTimeout)
   at Microsoft.Azure.ServiceBus.RetryPolicy.RunOperation(Func`1 operation, TimeSpan operationTimeout)
   at Microsoft.Azure.ServiceBus.Core.MessageReceiver.CompleteAsync(IEnumerable`1 lockTokens)
   at Data.Live.Processor.Host.WebJobs.MessageProcessorWebJob.ProcessMessageWithRetryAsync(Message message, IMessageReceiver messageReceiver) in D:\\MessageProcessorWebJob.cs:line 47
[19:12:29 INF] Executed 'MessageProcessorWebJob.ProcessMessageAsync' (Succeeded, Id=f8ec0157-c479-4338-aea6-dc0072a53912)
[19:12:29 INF] Executing 'MessageProcessorWebJob.ProcessMessageAsync' (Reason='New ServiceBus message detected on 'live-messages'.', Id=949af19c-070f-41ad-afb9-c33ae57815a7)
[19:12:29 INF] Trigger Details: MessageId: 5beeaf0afceb413d9d743d37d52a74ed, DeliveryCount: 1, EnqueuedTime: 04-09-19 16:10:46, LockedUntil: 31-12-99 23:59:59, SessionId: 2019_0466_LS009
[19:12:29 WRN] Processing message 5beeaf0afceb413d9d743d37d52a74ed for session 2019_0466_LS009. 
[19:12:30 ERR] Executed 'MessageProcessorWebJob.ProcessMessageAsync' (Failed, Id=036c3ec2-f4e1-4a97-9a62-2a4d4527eefe)
Microsoft.Azure.WebJobs.Host.FunctionInvocationException: Exception while executing function: MessageProcessorWebJob.ProcessMessageAsync ---> Microsoft.Azure.ServiceBus.SessionLockLostException: The session lock has expired on the MessageSession. Accept a new MessageSession.
   at Microsoft.Azure.ServiceBus.Core.MessageReceiver.DisposeMessagesAsync(IEnumerable`1 lockTokens, Outcome outcome)
   at Microsoft.Azure.ServiceBus.RetryPolicy.RunOperation(Func`1 operation, TimeSpan operationTimeout)
   at Microsoft.Azure.ServiceBus.RetryPolicy.RunOperation(Func`1 operation, TimeSpan operationTimeout)
   at Microsoft.Azure.ServiceBus.Core.MessageReceiver.AbandonAsync(String lockToken, IDictionary`2 propertiesToModify)
   at Data.Live.Processor.Host.WebJobs.MessageProcessorWebJob.ProcessMessageWithRetryAsync(Message message, IMessageReceiver messageReceiver) in D:\\MessageProcessorWebJob.cs:line 69
   at Data.Live.Processor.Host.WebJobs.MessageProcessorWebJob.ProcessMessageAsync(Message message, IMessageSession messageSession, Int32 deliveryCount) in D:\\MessageProcessorWebJob.cs:line 34
   at Microsoft.Azure.WebJobs.Host.Executors.VoidTaskMethodInvoker`2.InvokeAsync(TReflected instance, Object[] arguments) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\VoidTaskMethodInvoker.cs:line 21
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`2.InvokeAsync(Object instance, Object[] arguments) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionInvoker.cs:line 52
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.InvokeAsync(IFunctionInvoker invoker, ParameterHelper parameterHelper, CancellationTokenSource timeoutTokenSource, CancellationTokenSource functionCancellationTokenSource, Boolean throwOnTimeout, TimeSpan timerInterval, IFunctionInstance instance) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 585
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithWatchersAsync(IFunctionInstanceEx instance, ParameterHelper parameterHelper, ILogger logger, CancellationTokenSource functionCancellationTokenSource) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 534
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstanceEx instance, ParameterHelper parameterHelper, IFunctionOutputDefinition outputDefinition, ILogger logger, CancellationTokenSource functionCancellationTokenSource) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 470
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstanceEx instance, FunctionStartedMessage message, FunctionInstanceLogEntry instanceLogEntry, ParameterHelper parameterHelper, ILogger logger, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 279
   --- End of inner exception stack trace ---
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstanceEx instance, FunctionStartedMessage message, FunctionInstanceLogEntry instanceLogEntry, ParameterHelper parameterHelper, ILogger logger, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 325
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.TryExecuteAsyncCore(IFunctionInstanceEx functionInstance, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 117
[19:12:30 ERR] null
Microsoft.Azure.WebJobs.Host.FunctionInvocationException: Exception while executing function: MessageProcessorWebJob.ProcessMessageAsync ---> Microsoft.Azure.ServiceBus.SessionLockLostException: The session lock has expired on the MessageSession. Accept a new MessageSession.
   at Microsoft.Azure.ServiceBus.Core.MessageReceiver.DisposeMessagesAsync(IEnumerable`1 lockTokens, Outcome outcome)
   at Microsoft.Azure.ServiceBus.RetryPolicy.RunOperation(Func`1 operation, TimeSpan operationTimeout)
   at Microsoft.Azure.ServiceBus.RetryPolicy.RunOperation(Func`1 operation, TimeSpan operationTimeout)
   at Microsoft.Azure.ServiceBus.Core.MessageReceiver.AbandonAsync(String lockToken, IDictionary`2 propertiesToModify)
   at Data.Live.Processor.Host.WebJobs.MessageProcessorWebJob.ProcessMessageWithRetryAsync(Message message, IMessageReceiver messageReceiver) in D:\Projects\\MessageProcessorWebJob.cs:line 69
   at Data.Live.Processor.Host.WebJobs.MessageProcessorWebJob.ProcessMessageAsync(Message message, IMessageSession messageSession, Int32 deliveryCount) in D:\\MessageProcessorWebJob.cs:line 34
   at Microsoft.Azure.WebJobs.Host.Executors.VoidTaskMethodInvoker`2.InvokeAsync(TReflected instance, Object[] arguments) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\VoidTaskMethodInvoker.cs:line 21
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`2.InvokeAsync(Object instance, Object[] arguments) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionInvoker.cs:line 52
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.InvokeAsync(IFunctionInvoker invoker, ParameterHelper parameterHelper, CancellationTokenSource timeoutTokenSource, CancellationTokenSource functionCancellationTokenSource, Boolean throwOnTimeout, TimeSpan timerInterval, IFunctionInstance instance) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 585
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithWatchersAsync(IFunctionInstanceEx instance, ParameterHelper parameterHelper, ILogger logger, CancellationTokenSource functionCancellationTokenSource) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 534
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstanceEx instance, ParameterHelper parameterHelper, IFunctionOutputDefinition outputDefinition, ILogger logger, CancellationTokenSource functionCancellationTokenSource) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 470
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstanceEx instance, FunctionStartedMessage message, FunctionInstanceLogEntry instanceLogEntry, ParameterHelper parameterHelper, ILogger logger, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 279
   --- End of inner exception stack trace ---
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstanceEx instance, FunctionStartedMessage message, FunctionInstanceLogEntry instanceLogEntry, ParameterHelper parameterHelper, ILogger logger, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 325
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.TryExecuteAsyncCore(IFunctionInstanceEx functionInstance, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 117
```

**Comment by alrod** [comment]
@alex-zyl, can you please try to use latest package?https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.ServiceBus/4.1.0.
Does it work for you?

**Comment by alrod** [comment]
The issue is not reproducabple in the latest nuget package: https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.ServiceBus/4.1.0
