### ISSUE TITLE
InvalidOperationException receiving message as POCO

### ISSUE THREAD

**Issue by brandonh-msft** [Azure/azure-functions-servicebus-extension#92]
Extension nupkg version: 4.1.2

Function signature:
```csharp
        [FunctionName(nameof(ServiceBusQueueTriggeredFunction_AsPOCO))]
        public static void ServiceBusQueueTriggeredFunction_AsPOCO(
            [ServiceBusTrigger("sam-load-testing-objectq", Connection = "ServiceBusConnectionString")] Payload message,
            ILogger log) => log.LogInformation($@"Read Payload from message: {JsonSerializer.Serialize(message)}");
```

`Payload` definition:
```csharp
public class Payload
{
    public string Key { get; set; }
    public JsonElement Value { get; set; }
}
```

`Payload` posted:
```json
{
    "Key":"foo",
    "Value":{
        "bar":"baz",
        "no": 1
    }
}
```

![image](https://user-images.githubusercontent.com/20270743/84707215-29dfe580-af13-11ea-9a1d-df5a4dd71e68.png)

Exception received:
~~~
Microsoft.Azure.WebJobs.Host.FunctionInvocationException: Exception while executing function: ServiceBusQueueTriggeredFunction_AsPOCO
 ---> System.InvalidOperationException: Operation is not valid due to the current state of the object.
   at System.Text.Json.JsonElement.WriteTo(Utf8JsonWriter writer)
   at System.Text.Json.Serialization.Converters.JsonConverterJsonElement.Write(Utf8JsonWriter writer, JsonElement value, JsonSerializerOptions options)
   at System.Text.Json.JsonPropertyInfoNotNullable`4.OnWrite(WriteStackFrame& current, Utf8JsonWriter writer)
   at System.Text.Json.JsonPropertyInfo.Write(WriteStack& state, Utf8JsonWriter writer)
   at System.Text.Json.JsonSerializer.Write(Utf8JsonWriter writer, Int32 originalWriterDepth, Int32 flushThreshold, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.JsonSerializer.WriteCore(Utf8JsonWriter writer, Object value, Type type, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.WriteCore(PooledByteBufferWriter output, Object value, Type type, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.WriteCoreString(Object value, Type type, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Serialize[TValue](TValue value, JsonSerializerOptions options)
   at Functions.ServiceBusTriggered.QueueTriggered.ServiceBusQueueTriggeredFunction_AsPOCO(Payload message, ILogger log) in /home/vsts/work/1/s/functions/dotnet/ServiceBusTriggered/QueueTriggered.cs:line 20
   at lambda_method(Closure , QueueTriggered , Object[] )
   at Microsoft.Azure.WebJobs.Host.Executors.VoidMethodInvoker`2.InvokeAsync(TReflected instance, Object[] arguments) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\VoidMethodInvoker.cs:line 20
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`2.InvokeAsync(Object instance, Object[] arguments) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionInvoker.cs:line 52
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.InvokeAsync(IFunctionInvoker invoker, ParameterHelper parameterHelper, CancellationTokenSource timeoutTokenSource, CancellationTokenSource functionCancellationTokenSource, Boolean throwOnTimeout, TimeSpan timerInterval, IFunctionInstance instance) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 585
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithWatchersAsync(IFunctionInstanceEx instance, ParameterHelper parameterHelper, ILogger logger, CancellationTokenSource functionCancellationTokenSource) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 532
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstanceEx instance, ParameterHelper parameterHelper, IFunctionOutputDefinition outputDefinition, ILogger logger, CancellationTokenSource functionCancellationTokenSource) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 468
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstanceEx instance, FunctionStartedMessage message, FunctionInstanceLogEntry instanceLogEntry, ParameterHelper parameterHelper, ILogger logger, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 278
   --- End of inner exception stack trace ---
   at Microsoft.Azure.WebJobs.ServiceBus.MessageProcessor.CompleteProcessingMessageAsync(Message message, FunctionResult result, CancellationToken cancellationToken)
   at Microsoft.Azure.WebJobs.ServiceBus.Listeners.ServiceBusListener.ProcessMessageAsync(Message message, CancellationToken cancellationToken)
   at Microsoft.Azure.ServiceBus.MessageReceivePump.MessageDispatchTask(Message message)
~~~

**Comment by Marvin-Brouwer** [comment]
I think this might have something to do with this:
![image](https://user-images.githubusercontent.com/5499778/104467243-66adb100-55b6-11eb-9d6a-3aba015b225f.png)
It appears that the Service bus returns a JSON object with a serialized JSON object in the Result property.
Not only does this require a wrapping class or struct but also we now have to deserialize it twice.

I'm using
- dotnet core 3.1
- azure functions 3
- Microsoft.Azure.Functions.Extensions Version="1.1.0"
- Microsoft.Azure.WebJobs.Extensions.ServiceBus Version="4.2.0" 
- Microsoft.NET.Sdk.Functions Version="3.0.11"
- System.Runtime Version="4.3.1"

I hope this helps with triaging

**Comment by hossam-nasr** [comment]
@brandonh-msft It looks like this is due to incompatibility between `Newtonsoft.Json` types/methods and `System.Text.Json` ones. In our extension code [here](https://github.com/Azure/azure-functions-servicebus-extension/blob/541b425f28411aeb0cbd8c8c5685de8a0218f64e/src/Microsoft.Azure.WebJobs.Extensions.ServiceBus/Triggers/MessageToPocoConverter.cs#L50), we use the `Newtonsoft.Json.JsonConvert.DeserializeObject<T>()` method to deserialize JSONs. Meanwhile, in your repro, you are using the `System.Text.JsonSerializer.Serialize()` method to serialize it back, and also using the `System.Text.Json.JsonElement` type in your class definition. These methods/types don't seem to work well together. My suggestion would be to use the `Newtonsoft.Json` types/methods for your function too, and it should work as expected.

For example, changing your class definition to be:

```C#
using Newtonsoft.Json;

public class Payload
{
    public string Key { get; set; }
    public JObject Value { get; set; }
}
```

And your function signature to:

```C#
using Newtonsoft.Json;

[FunctionName(nameof(ServiceBusQueueTriggeredFunction_AsPOCO))]
public static void ServiceBusQueueTriggeredFunction_AsPOCO(
    [ServiceBusTrigger("sam-load-testing-objectq", Connection = "ServiceBusConnectionString")] Payload message,
    ILogger log) => log.LogInformation($@"Read Payload from message: {JsonConvert.SerializeObject(message)}");
```

Should yield the expected result:

```
Read payload from message: {"Key":"foo","Value":{"bar":"baz","no":1}}
```

Closing this issue with this workaround, but feel free to reopen if this doesn't work or if you continue to face problems.
